//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTCK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBanNuocHoaEntities : DbContext
    {
        public QuanLyBanNuocHoaEntities()
            : base("name=QuanLyBanNuocHoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CTHD> tb_CTHD { get; set; }
        public virtual DbSet<tb_HangHoa> tb_HangHoa { get; set; }
        public virtual DbSet<tb_HoaDon> tb_HoaDon { get; set; }
        public virtual DbSet<tb_KhachHang> tb_KhachHang { get; set; }
        public virtual DbSet<tb_LoaiHangHoa> tb_LoaiHangHoa { get; set; }
        public virtual DbSet<tb_NhanVien> tb_NhanVien { get; set; }
    }
}
