//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTCK
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTHD
    {
        public int MaHD { get; set; }
        public int MaHH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual tb_HangHoa tb_HangHoa { get; set; }
        public virtual tb_HoaDon tb_HoaDon { get; set; }
    }
}
